FROM rocker/verse:latest

RUN R -e "install.packages(c('gridExtra', 'caret', 'randomForest', 'Polychrome', 'FactoMineR', 'factoextra', 'Rtsne'), dependencies=TRUE, repos='http://cran.rstudio.com/')"

